### ISSUE TITLE
JOSS paper

### ISSUE THREAD

**Issue by jsta** [VeinsOfTheEarth/rabpro#100]
## tasks
* [x] complete docstrings, search `[summary]`, `[description]`, `Desc.`, and `[type]` @jsta
> There might be semi-complete entries but at least all the placeholders have been addressed.
* [x] code cleanup (remove commented centerline code) @jsta 
* [x] packaging (conda + pypi) workflow, rewrite installation instructions @jsta 
* [x] data documentation
> I removed the text on manually downloading HydroBASINS and MERIT. The docs now only cover the automated `rabpro download` utilities.
* [x] GEE setup
> I removed the text on manually adding your own user assets and instead point to opening an issue.
* [x] create example notebook of (nearly) all possible subbasin_stats call types @jsta
* [x] mint new release and upload to pypi + conda 
* [x] elev_profile improvement adding upstream walking @jonschwenk 
* [x] address https://github.com/VeinsOfTheEarth/rabpro/issues/112 @jonschwenk 
* [x] write paper
* [x] remove hexagon from logo @jsta 
* [x] fix tests and examples after recent commits that change syntax and arguments @jonschwenk 
* [ ] check all public function docstrings for completeness and clarity @jonschwenk 
* [x] move download functions into `data_utils.py` @jonschwenk 
* [x] update docs to include download functionality (add manual instructions?) @jsta

**Comment by jsta** [comment]
Created a branch called [paper](https://github.com/VeinsOfTheEarth/rabpro/tree/paper) to test the joss template

**Comment by jonschwenk** [comment]
Exciting, let's make it happen!

**Comment by jsta** [comment]
Google Doc at https://docs.google.com/document/d/1a3wqF_nAsy0vPSKNWc6PK7tg1Yzybnit2bRWVrYfyCQ/edit?usp=sharing

**Comment by jsta** [comment]
I'm thinking as part of the docstring cleanup I'll  pre-append `_` to some functions marking them as private and removing them from the autodocumentation. For example I don't see any reason why `elev_profile.get_rc_values` needs to be in the website docs.

**Comment by jonschwenk** [comment]
> I'm thinking as part of the docstring cleanup I'll pre-append `_` to some functions marking them as private and removing them from the autodocumentation. For example, I don't see any reason why `elev_profile.get_rc_values` needs to be in the website docs.

I concur. It was only after Tal developed that I realized the significance of "_". Many functions could be privatized such.

**Comment by jsta** [comment]
I did this for functions with incomplete docstrings that I felt could be hidden, those with complete docstrings I left public.

**Comment by jsta** [comment]
I propose a demo figure with the following panels:

1) map showing a coordinate point over a DEM
2) map showing a "centerline" over a delineated basin
3) a line plot showing the stats of some GEE attribute through time

**Comment by jonschwenk** [comment]
I was thinking something like 4 panels a-d:
(a) 
Aerial image with coordinate
(b) 
[top] DEM with MERIT-derived watershed outline
[bottom] HydroBasins polygons with HB-derived watershed outline
(c) 
[top] flowline plotted on DEM
[bottom] elevation profile of flowline
(d) 
[top] stacked watersheds, each representing a different stat (maybe precip, temp, NDVI)
[bottom] time series of precip and temperature

It's a lot but I think it demonstrates everything. I can do (a)-(c) if you could handle (d)? I will try to get the basin gdf tonight.

**Comment by jonschwenk** [comment]
See https://github.com/VeinsOfTheEarth/rabpro/tree/main/docs/paper_fig for the code to generate the basins. I had the geopackages there too but they're git ignored, apparently.

**Comment by jonschwenk** [comment]
Paper is complete pending any additional minor edits by @jsta and @tzussman. I will plan on submitting this evening, so please get any final edits in before then.
